# Generated by Django 3.1.6 on 2021-04-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210414_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
